
language: objective-c
xcode_project: Hackerspaces.xcodeproj
xcode_scheme: HackerspacesTests
osx_image: xcode9

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0' -project Hackerspaces.xcodeproj -scheme Hackerspaces CODE_SIGNING_REQUIRED=NO
